#!/usr/bin/env bash
# AWS config 組み立て（config.d/*.conf → ~/.aws/config）

# INI ファイルからセクション名一覧を抽出
_ini_sections() {
  grep -o '^\[.*\]' <<< "$1" | sort -u
}

# INI ファイルから指定セクションの全体（ヘッダー＋ボディ）を抽出
_ini_extract_section() {
  local content="$1" section="$2"
  local in_section=false
  local result=""
  while IFS= read -r line; do
    if [ "$line" = "$section" ]; then
      in_section=true
      result+="$line"$'\n'
    elif [[ "$line" =~ ^\[.*\] ]]; then
      in_section=false
    elif $in_section; then
      result+="$line"$'\n'
    fi
  done <<< "$content"
  printf '%s' "$result"
}

# ~/.aws/config が外部変更されていたら差分を config.d に取り込む
_import_aws_config() {
  local config_d="$1"
  local dest="$HOME/.aws/config"
  local imported="$config_d/90-imported.conf"

  [ -f "$dest" ] || return 0

  # 自動生成ヘッダーがなければ、手動管理のファイル → 丸ごと取り込み
  if ! grep -q "Auto-generated by dotfiles" "$dest"; then
    echo "インポート: ~/.aws/config を config.d に取り込みます"
    cp "$dest" "$imported"
    echo "  → $(basename "$imported") に保存しました"
    echo "  適切なファイル (10-<org>.conf 等) に整理してください"
    return 0
  fi

  # config.d の現在の内容と比較
  local expected
  expected="$(_build_aws_config "$config_d")"

  if [ "$(cat "$dest")" = "$expected" ]; then
    return 0  # 変更なし
  fi

  echo "外部変更検出: ~/.aws/config が直接編集されています"

  # ヘッダーを除去した現在の内容
  local current_body
  current_body="$(sed '/^# Auto-generated/d; /^# Edit .config/d' "$dest")"

  # config.d の既存内容を結合
  local existing=""
  while IFS= read -r -d '' f; do
    existing+="$(cat "$f")"
    existing+=$'\n'
  done < <(find "$config_d" -name '*.conf' -type f -print0 2>/dev/null | sort -z)

  # セクション単位で差分を検出
  local existing_sections current_sections
  existing_sections="$(_ini_sections "$existing")"
  current_sections="$(_ini_sections "$current_body")"

  # current にだけあるセクション
  local new_sections
  new_sections="$(comm -13 <(echo "$existing_sections") <(echo "$current_sections"))"

  if [ -z "$new_sections" ]; then
    return 0
  fi

  # 新規セクションを順序を保って抽出
  local result=""
  while IFS= read -r section; do
    [ -z "$section" ] && continue
    result+="$(_ini_extract_section "$current_body" "$section")"
    result+=$'\n'
  done <<< "$new_sections"

  if [ -n "$result" ]; then
    printf '%s' "$result" > "$imported"
    echo "  → $(basename "$imported") に新規セクションを保存しました:"
    grep '^\[' "$imported" | sed 's/^/    /'
    echo "  適切なファイルに移動し、90-imported.conf を削除してください"
  fi
}

# config.d/*.conf から結合コンテンツを生成（stdout に出力）
_build_aws_config() {
  local config_d="$1"
  local content="# Auto-generated by dotfiles — do not edit directly
# Edit .config/aws/config.d/*.conf and run install.sh
"
  local files=()
  while IFS= read -r -d '' f; do
    files+=("$f")
  done < <(find "$config_d" -name '*.conf' -type f -print0 2>/dev/null | sort -z)

  for f in "${files[@]}"; do
    content+="$(cat "$f")"
    content+=$'\n'
  done

  printf '%s' "$content"
}

assemble_aws_config() {
  local config_d="$DOTFILES_DIR/.config/aws/config.d"
  local dest="$HOME/.aws/config"

  if [ ! -d "$config_d" ]; then
    echo "スキップ: $config_d が存在しません"
    return
  fi

  # config.d 内にファイルがなければスキップ
  local file_count
  file_count=$(find "$config_d" -name '*.conf' -type f 2>/dev/null | wc -l)
  if [ "$file_count" -eq 0 ]; then
    echo "スキップ: config.d にファイルがありません"
    return
  fi

  mkdir -p "$(dirname "$dest")"

  # 外部変更の取り込み（90-imported.conf が追加される可能性あり）
  _import_aws_config "$config_d"

  # 結合して出力（import 後に再ビルド）
  local new_content
  new_content="$(_build_aws_config "$config_d")"

  # 差分がなければスキップ
  if [ -f "$dest" ] && [ "$(cat "$dest")" = "$new_content" ]; then
    echo "済み:     $dest"
    return
  fi

  printf '%s' "$new_content" > "$dest"
  echo "生成:     $dest"
}
